services:
  # Backend API service
  - type: web
    name: crypto-monitor-api
    env: go
    region: oregon  # or choose a region closer to your users
    buildCommand: cd backend && go build -o main ./cmd/server/
    startCommand: cd backend && ./main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: crypto-monitor-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true # Automatically generates a secure random value
      - key: PORT
        value: 8080
      - key: GIN_MODE
        value: release

  # Frontend service
  - type: web
    name: crypto-monitor-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: NODE_ENV
        value: production

databases:
  - name: crypto-monitor-db
    databaseName: cryptodb
    user: crypto_user
    plan: free # or choose a paid plan if needed

# Specify routes/domains if needed
routes:
  - type: rewrite
    source: /*
    destination: /index.html
