apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-monitor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crypto-monitor
  template:
    metadata:
      labels:
        app: crypto-monitor
    spec:
      containers:
      - name: crypto-monitor
        image: ghcr.io/yourusername/crypto-monitor:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: crypto-monitor-secrets
              key: database-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: crypto-monitor-secrets
              key: jwt-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5