openapi: 3.0.0
info:
  title: Crypto Monitor API
  version: 1.0.0
  description: API documentation for the Crypto Monitor application

servers:
  - url: http://localhost:8080/api
    description: Development server

paths:
  /auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'

  /market/data/{symbol}:
    get:
      summary: Get market data for a specific symbol
      parameters:
        - name: symbol
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Market data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketData'

components:
  schemas:
    AuthResponse:
      type: object
      properties:
        token:
          type: string
        user:
          $ref: '#/components/schemas/User'

    User:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string

    MarketData:
      type: object
      properties:
        symbol:
          type: string
        price:
          type: number
        change24h:
          type: number
        volume24h:
          type: number